fcoeadm: Fix compilation warning
fcoeadm.c: In function ‘main’:
fcoeadm.c:322: warning: implicit declaration of function ‘fcoe_validate_fcoe_conn’

This patch adds fcoe_validate_fcoe_conn to fcoe_utils.h.

This patch additionally removes the undefined and unused valid_ifname routine.

Signed-off-by: Robert Love <robert.w.love@intel.com>